export const colors = {
    primary: '#3843D0',
    success: '#4ADE80',
    warning: '#FACC15',
    error: '#F75555',
    grey50: '#F8FAFC',
    grey100: '#F1F5F9',
    grey200: '#E2E8F0',
    grey300: '#CBD5E1',
    grey400: '#94A3B8',
    grey500: '#64748B',
    grey600: '#475569',
    grey700: '#475569',
    grey800: '#1E293B',
    grey900: '#0F172A',
    white: '#FFFFFF',
    black: '#0F172A',
    background: '#F1F5F9',
    opacity: 'rgba(15, 23, 42, 0.5)',
}

export const heading = {
    h1: 48,
    h2: 40,
    h3: 32,
    h4: 24,
    h5: 20,
    h6: 18,
}

export const body = {
    xl: 18,
    large: 16,
    medium: 14,
    small: 12,
    xsmall: 10,
}

export const weight = {
    bold: 'bold',
    semibold: 'semibold',
    medium: '500',
    regular: 'regular',
}

export const text = {
    HeyDev: 'Hey, Dev 👋',
    KeepUpTheGoodWork: 'Keep up the good work!',
    QuienEs: '¿Quién es el famoso?',
    PresionaParaElegir: 'Presiona para elegir una foto',
    SeleccionaUnaFoto: 'Selecciona una foto',
    GaleriaDeFotos: 'Galeria de fotos',
    Camara: 'Cámara',
    Subiendo: 'Subiendo...',
    EsUnFamoso: '¿Es un famoso?',
    Listo: 'Listo',
    HuboUnError: 'Hubo un error',
    Buscando: 'Buscando...',
    NoSeEncontro: 'No se encontró',
    Error: 'Error de red o de servidor',
    Cerrar: 'Cerrar',
    Hombre: 'Hombre',
    Mujer: 'Mujer',
    Popularidad: 'Popularidad:',
    Star: ' ⭐',
    Peliculas: 'Peliculas',
    DarkContent: 'dark-content',
    apiNomada: 'https://whois.nomada.cloud/upload',
    nomadaKey: 'MDU5ZGIzNzktYTIyMy00M2FkLWIxMGYtMzZkYTM2NzkwN2Vl',
    alertTitle: 'Ops! 😅',
    alertText: 'Solo se aceptan archivos jpg o png',
    alertClose: 'Aceptar',
    apiTheMovieDB: 'https://api.themoviedb.org/3/search/person?api_key=30db1237b9167f8afaf9e065b90d16b8&language=en-US&query=',
    apiTheMovieDBSecondPart: '&page=1&include_adult=false',
    apiTheMovieDBActorImage: 'https://image.tmdb.org/t/p/original',
    Hombre: 'Hombre',
    Mujer: 'Mujer',
    WithoutInfo: 'Without information',
    WithoutMovieInfo: 'Sabemos quien es pero no tenemos informacion de sus peliculas 😥',
}